# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Exchanges(BaseModel):
    """
    Exchanges
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="exchange ID")
    name: Optional[StrictStr] = Field(default=None, description="exchange name")
    year_established: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="exchange established year")
    country: Optional[StrictStr] = Field(default=None, description="exchange country")
    description: Optional[StrictStr] = Field(default=None, description="exchange description")
    url: Optional[StrictStr] = Field(default=None, description="exchange website url")
    image: Optional[StrictStr] = Field(default=None, description="exchange image url")
    has_trading_incentive: Optional[StrictBool] = Field(default=None, description="exchange trading incentive")
    trust_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="exchange trust score")
    trust_score_rank: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="exchange trust score rank")
    trade_volume_24h_btc: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="exchange trade volume in BTC in 24 hours")
    trade_volume_24h_btc_normalized: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="normalized trading volume by traffic in BTC in 24 hours <br> *refers to [`this blog`](https://blog.coingecko.com/trust-score/).")
    __properties: ClassVar[List[str]] = ["id", "name", "year_established", "country", "description", "url", "image", "has_trading_incentive", "trust_score", "trust_score_rank", "trade_volume_24h_btc", "trade_volume_24h_btc_normalized"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Exchanges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Exchanges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "year_established": obj.get("year_established"),
            "country": obj.get("country"),
            "description": obj.get("description"),
            "url": obj.get("url"),
            "image": obj.get("image"),
            "has_trading_incentive": obj.get("has_trading_incentive"),
            "trust_score": obj.get("trust_score"),
            "trust_score_rank": obj.get("trust_score_rank"),
            "trade_volume_24h_btc": obj.get("trade_volume_24h_btc"),
            "trade_volume_24h_btc_normalized": obj.get("trade_volume_24h_btc_normalized")
        })
        return _obj


