# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from coingecko_python.models.token_data_attributes_volume_usd import TokenDataAttributesVolumeUsd
from typing import Optional, Set
from typing_extensions import Self

class TokenDataAttributes(BaseModel):
    """
    TokenDataAttributes
    """ # noqa: E501
    address: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    symbol: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    coingecko_coin_id: Optional[StrictStr] = None
    decimals: Optional[StrictInt] = None
    total_supply: Optional[StrictStr] = None
    price_usd: Optional[StrictStr] = None
    fdv_usd: Optional[StrictStr] = None
    total_reserve_in_usd: Optional[StrictStr] = None
    volume_usd: Optional[TokenDataAttributesVolumeUsd] = None
    market_cap_usd: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "name", "symbol", "image_url", "coingecko_coin_id", "decimals", "total_supply", "price_usd", "fdv_usd", "total_reserve_in_usd", "volume_usd", "market_cap_usd"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenDataAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of volume_usd
        if self.volume_usd:
            _dict['volume_usd'] = self.volume_usd.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenDataAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "name": obj.get("name"),
            "symbol": obj.get("symbol"),
            "image_url": obj.get("image_url"),
            "coingecko_coin_id": obj.get("coingecko_coin_id"),
            "decimals": obj.get("decimals"),
            "total_supply": obj.get("total_supply"),
            "price_usd": obj.get("price_usd"),
            "fdv_usd": obj.get("fdv_usd"),
            "total_reserve_in_usd": obj.get("total_reserve_in_usd"),
            "volume_usd": TokenDataAttributesVolumeUsd.from_dict(obj["volume_usd"]) if obj.get("volume_usd") is not None else None,
            "market_cap_usd": obj.get("market_cap_usd")
        })
        return _obj


