# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TrendingSearchNftsInnerData(BaseModel):
    """
    TrendingSearchNftsInnerData
    """ # noqa: E501
    floor_price: Optional[StrictStr] = Field(default=None, description="NFT collection floor price")
    floor_price_in_usd_24h_percentage_change: Optional[StrictStr] = Field(default=None, description="NFT collection floor price in usd 24 hours percentage change")
    h24_volume: Optional[StrictStr] = Field(default=None, description="NFT collection volume in 24 hours")
    h24_average_sale_price: Optional[StrictStr] = Field(default=None, description="NFT collection 24 hours average sale price")
    sparkline: Optional[StrictStr] = Field(default=None, description="NFT collection sparkline image url")
    content: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["floor_price", "floor_price_in_usd_24h_percentage_change", "h24_volume", "h24_average_sale_price", "sparkline", "content"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrendingSearchNftsInnerData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrendingSearchNftsInnerData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "floor_price": obj.get("floor_price"),
            "floor_price_in_usd_24h_percentage_change": obj.get("floor_price_in_usd_24h_percentage_change"),
            "h24_volume": obj.get("h24_volume"),
            "h24_average_sale_price": obj.get("h24_average_sale_price"),
            "sparkline": obj.get("sparkline"),
            "content": obj.get("content")
        })
        return _obj


