# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from coingecko-sdk.models.pool_data_inner_relationships_base_token import PoolDataInnerRelationshipsBaseToken
from typing import Optional, Set
from typing_extensions import Self

class CategoriesPoolsDataInnerRelationships(BaseModel):
    """
    CategoriesPoolsDataInnerRelationships
    """ # noqa: E501
    network: Optional[PoolDataInnerRelationshipsBaseToken] = None
    dex: Optional[PoolDataInnerRelationshipsBaseToken] = None
    base_token: Optional[PoolDataInnerRelationshipsBaseToken] = None
    quote_token: Optional[PoolDataInnerRelationshipsBaseToken] = None
    __properties: ClassVar[List[str]] = ["network", "dex", "base_token", "quote_token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CategoriesPoolsDataInnerRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of network
        if self.network:
            _dict['network'] = self.network.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dex
        if self.dex:
            _dict['dex'] = self.dex.to_dict()
        # override the default output from pydantic by calling `to_dict()` of base_token
        if self.base_token:
            _dict['base_token'] = self.base_token.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quote_token
        if self.quote_token:
            _dict['quote_token'] = self.quote_token.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CategoriesPoolsDataInnerRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "network": PoolDataInnerRelationshipsBaseToken.from_dict(obj["network"]) if obj.get("network") is not None else None,
            "dex": PoolDataInnerRelationshipsBaseToken.from_dict(obj["dex"]) if obj.get("dex") is not None else None,
            "base_token": PoolDataInnerRelationshipsBaseToken.from_dict(obj["base_token"]) if obj.get("base_token") is not None else None,
            "quote_token": PoolDataInnerRelationshipsBaseToken.from_dict(obj["quote_token"]) if obj.get("quote_token") is not None else None
        })
        return _obj


