# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from coingecko-sdk.models.nft_data_ath import NFTDataAth
from coingecko-sdk.models.nft_data_ath_change_percentage import NFTDataAthChangePercentage
from coingecko-sdk.models.nft_data_ath_date import NFTDataAthDate
from coingecko-sdk.models.nft_data_banner_image import NFTDataBannerImage
from coingecko-sdk.models.nft_data_explorers_inner import NFTDataExplorersInner
from coingecko-sdk.models.nft_data_floor_price import NFTDataFloorPrice
from coingecko-sdk.models.nft_data_floor_price14d_percentage_change import NFTDataFloorPrice14dPercentageChange
from coingecko-sdk.models.nft_data_floor_price1y_percentage_change import NFTDataFloorPrice1yPercentageChange
from coingecko-sdk.models.nft_data_floor_price24h_percentage_change import NFTDataFloorPrice24hPercentageChange
from coingecko-sdk.models.nft_data_floor_price30d_percentage_change import NFTDataFloorPrice30dPercentageChange
from coingecko-sdk.models.nft_data_floor_price60d_percentage_change import NFTDataFloorPrice60dPercentageChange
from coingecko-sdk.models.nft_data_floor_price7d_percentage_change import NFTDataFloorPrice7dPercentageChange
from coingecko-sdk.models.nft_data_image import NFTDataImage
from coingecko-sdk.models.nft_data_links import NFTDataLinks
from coingecko-sdk.models.nft_data_market_cap import NFTDataMarketCap
from coingecko-sdk.models.nft_data_market_cap24h_percentage_change import NFTDataMarketCap24hPercentageChange
from coingecko-sdk.models.nft_data_volume24h import NFTDataVolume24h
from coingecko-sdk.models.nft_data_volume24h_percentage_change import NFTDataVolume24hPercentageChange
from typing import Optional, Set
from typing_extensions import Self

class NFTData(BaseModel):
    """
    NFTData
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="NFT collection ID")
    contract_address: Optional[StrictStr] = Field(default=None, description="NFT collection contract address")
    asset_platform_id: Optional[StrictStr] = Field(default=None, description="NFT collection asset platform ID")
    name: Optional[StrictStr] = Field(default=None, description="NFT collection name")
    symbol: Optional[StrictStr] = Field(default=None, description="NFT collection symbol")
    image: Optional[NFTDataImage] = None
    banner_image: Optional[NFTDataBannerImage] = None
    description: Optional[StrictStr] = Field(default=None, description="NFT collection description")
    native_currency: Optional[StrictStr] = Field(default=None, description="NFT collection native currency")
    native_currency_symbol: Optional[StrictStr] = Field(default=None, description="NFT collection native currency symbol")
    market_cap_rank: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin market cap rank")
    floor_price: Optional[NFTDataFloorPrice] = None
    market_cap: Optional[NFTDataMarketCap] = None
    volume_24h: Optional[NFTDataVolume24h] = None
    floor_price_in_usd_24h_percentage_change: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection floor price in usd 24 hours percentage change")
    floor_price_24h_percentage_change: Optional[NFTDataFloorPrice24hPercentageChange] = None
    market_cap_24h_percentage_change: Optional[NFTDataMarketCap24hPercentageChange] = None
    volume_24h_percentage_change: Optional[NFTDataVolume24hPercentageChange] = None
    number_of_unique_addresses: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="number of unique address owning the NFTs")
    number_of_unique_addresses_24h_percentage_change: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="number of unique address owning the NFTs 24 hours percentage change")
    volume_in_usd_24h_percentage_change: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection volume in usd 24 hours percentage change")
    total_supply: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection total supply")
    one_day_sales: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection one day sales")
    one_day_sales_24h_percentage_change: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection one day sales 24 hours percentage change")
    one_day_average_sale_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection one day average sale price")
    one_day_average_sale_price_24h_percentage_change: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection one day average sale price 24 hours percentage change")
    links: Optional[NFTDataLinks] = None
    floor_price_7d_percentage_change: Optional[NFTDataFloorPrice7dPercentageChange] = None
    floor_price_14d_percentage_change: Optional[NFTDataFloorPrice14dPercentageChange] = None
    floor_price_30d_percentage_change: Optional[NFTDataFloorPrice30dPercentageChange] = None
    floor_price_60d_percentage_change: Optional[NFTDataFloorPrice60dPercentageChange] = None
    floor_price_1y_percentage_change: Optional[NFTDataFloorPrice1yPercentageChange] = None
    explorers: Optional[List[NFTDataExplorersInner]] = Field(default=None, description="NFT collection block explorers links")
    user_favorites_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="NFT collection user favorites count")
    ath: Optional[NFTDataAth] = None
    ath_change_percentage: Optional[NFTDataAthChangePercentage] = None
    ath_date: Optional[NFTDataAthDate] = None
    __properties: ClassVar[List[str]] = ["id", "contract_address", "asset_platform_id", "name", "symbol", "image", "banner_image", "description", "native_currency", "native_currency_symbol", "market_cap_rank", "floor_price", "market_cap", "volume_24h", "floor_price_in_usd_24h_percentage_change", "floor_price_24h_percentage_change", "market_cap_24h_percentage_change", "volume_24h_percentage_change", "number_of_unique_addresses", "number_of_unique_addresses_24h_percentage_change", "volume_in_usd_24h_percentage_change", "total_supply", "one_day_sales", "one_day_sales_24h_percentage_change", "one_day_average_sale_price", "one_day_average_sale_price_24h_percentage_change", "links", "floor_price_7d_percentage_change", "floor_price_14d_percentage_change", "floor_price_30d_percentage_change", "floor_price_60d_percentage_change", "floor_price_1y_percentage_change", "explorers", "user_favorites_count", "ath", "ath_change_percentage", "ath_date"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NFTData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image
        if self.image:
            _dict['image'] = self.image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of banner_image
        if self.banner_image:
            _dict['banner_image'] = self.banner_image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price
        if self.floor_price:
            _dict['floor_price'] = self.floor_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of market_cap
        if self.market_cap:
            _dict['market_cap'] = self.market_cap.to_dict()
        # override the default output from pydantic by calling `to_dict()` of volume_24h
        if self.volume_24h:
            _dict['volume_24h'] = self.volume_24h.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price_24h_percentage_change
        if self.floor_price_24h_percentage_change:
            _dict['floor_price_24h_percentage_change'] = self.floor_price_24h_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of market_cap_24h_percentage_change
        if self.market_cap_24h_percentage_change:
            _dict['market_cap_24h_percentage_change'] = self.market_cap_24h_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of volume_24h_percentage_change
        if self.volume_24h_percentage_change:
            _dict['volume_24h_percentage_change'] = self.volume_24h_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price_7d_percentage_change
        if self.floor_price_7d_percentage_change:
            _dict['floor_price_7d_percentage_change'] = self.floor_price_7d_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price_14d_percentage_change
        if self.floor_price_14d_percentage_change:
            _dict['floor_price_14d_percentage_change'] = self.floor_price_14d_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price_30d_percentage_change
        if self.floor_price_30d_percentage_change:
            _dict['floor_price_30d_percentage_change'] = self.floor_price_30d_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price_60d_percentage_change
        if self.floor_price_60d_percentage_change:
            _dict['floor_price_60d_percentage_change'] = self.floor_price_60d_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of floor_price_1y_percentage_change
        if self.floor_price_1y_percentage_change:
            _dict['floor_price_1y_percentage_change'] = self.floor_price_1y_percentage_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in explorers (list)
        _items = []
        if self.explorers:
            for _item_explorers in self.explorers:
                if _item_explorers:
                    _items.append(_item_explorers.to_dict())
            _dict['explorers'] = _items
        # override the default output from pydantic by calling `to_dict()` of ath
        if self.ath:
            _dict['ath'] = self.ath.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ath_change_percentage
        if self.ath_change_percentage:
            _dict['ath_change_percentage'] = self.ath_change_percentage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ath_date
        if self.ath_date:
            _dict['ath_date'] = self.ath_date.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NFTData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "contract_address": obj.get("contract_address"),
            "asset_platform_id": obj.get("asset_platform_id"),
            "name": obj.get("name"),
            "symbol": obj.get("symbol"),
            "image": NFTDataImage.from_dict(obj["image"]) if obj.get("image") is not None else None,
            "banner_image": NFTDataBannerImage.from_dict(obj["banner_image"]) if obj.get("banner_image") is not None else None,
            "description": obj.get("description"),
            "native_currency": obj.get("native_currency"),
            "native_currency_symbol": obj.get("native_currency_symbol"),
            "market_cap_rank": obj.get("market_cap_rank"),
            "floor_price": NFTDataFloorPrice.from_dict(obj["floor_price"]) if obj.get("floor_price") is not None else None,
            "market_cap": NFTDataMarketCap.from_dict(obj["market_cap"]) if obj.get("market_cap") is not None else None,
            "volume_24h": NFTDataVolume24h.from_dict(obj["volume_24h"]) if obj.get("volume_24h") is not None else None,
            "floor_price_in_usd_24h_percentage_change": obj.get("floor_price_in_usd_24h_percentage_change"),
            "floor_price_24h_percentage_change": NFTDataFloorPrice24hPercentageChange.from_dict(obj["floor_price_24h_percentage_change"]) if obj.get("floor_price_24h_percentage_change") is not None else None,
            "market_cap_24h_percentage_change": NFTDataMarketCap24hPercentageChange.from_dict(obj["market_cap_24h_percentage_change"]) if obj.get("market_cap_24h_percentage_change") is not None else None,
            "volume_24h_percentage_change": NFTDataVolume24hPercentageChange.from_dict(obj["volume_24h_percentage_change"]) if obj.get("volume_24h_percentage_change") is not None else None,
            "number_of_unique_addresses": obj.get("number_of_unique_addresses"),
            "number_of_unique_addresses_24h_percentage_change": obj.get("number_of_unique_addresses_24h_percentage_change"),
            "volume_in_usd_24h_percentage_change": obj.get("volume_in_usd_24h_percentage_change"),
            "total_supply": obj.get("total_supply"),
            "one_day_sales": obj.get("one_day_sales"),
            "one_day_sales_24h_percentage_change": obj.get("one_day_sales_24h_percentage_change"),
            "one_day_average_sale_price": obj.get("one_day_average_sale_price"),
            "one_day_average_sale_price_24h_percentage_change": obj.get("one_day_average_sale_price_24h_percentage_change"),
            "links": NFTDataLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "floor_price_7d_percentage_change": NFTDataFloorPrice7dPercentageChange.from_dict(obj["floor_price_7d_percentage_change"]) if obj.get("floor_price_7d_percentage_change") is not None else None,
            "floor_price_14d_percentage_change": NFTDataFloorPrice14dPercentageChange.from_dict(obj["floor_price_14d_percentage_change"]) if obj.get("floor_price_14d_percentage_change") is not None else None,
            "floor_price_30d_percentage_change": NFTDataFloorPrice30dPercentageChange.from_dict(obj["floor_price_30d_percentage_change"]) if obj.get("floor_price_30d_percentage_change") is not None else None,
            "floor_price_60d_percentage_change": NFTDataFloorPrice60dPercentageChange.from_dict(obj["floor_price_60d_percentage_change"]) if obj.get("floor_price_60d_percentage_change") is not None else None,
            "floor_price_1y_percentage_change": NFTDataFloorPrice1yPercentageChange.from_dict(obj["floor_price_1y_percentage_change"]) if obj.get("floor_price_1y_percentage_change") is not None else None,
            "explorers": [NFTDataExplorersInner.from_dict(_item) for _item in obj["explorers"]] if obj.get("explorers") is not None else None,
            "user_favorites_count": obj.get("user_favorites_count"),
            "ath": NFTDataAth.from_dict(obj["ath"]) if obj.get("ath") is not None else None,
            "ath_change_percentage": NFTDataAthChangePercentage.from_dict(obj["ath_change_percentage"]) if obj.get("ath_change_percentage") is not None else None,
            "ath_date": NFTDataAthDate.from_dict(obj["ath_date"]) if obj.get("ath_date") is not None else None
        })
        return _obj


