# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.api.contract_api import ContractApi


class TestContractApi(unittest.TestCase):
    """ContractApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractApi()

    def tearDown(self) -> None:
        pass

    def test_coins_contract_address(self) -> None:
        """Test case for coins_contract_address

        Coin Data by Token Address
        """
        pass

    def test_contract_address_market_chart(self) -> None:
        """Test case for contract_address_market_chart

        Coin Historical Chart Data by Token Address
        """
        pass

    def test_contract_address_market_chart_range(self) -> None:
        """Test case for contract_address_market_chart_range

        Coin Historical Chart Data within Time Range by Token Address
        """
        pass


if __name__ == '__main__':
    unittest.main()
