# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.api.asset_platforms_api import AssetPlatformsApi


class TestAssetPlatformsApi(unittest.TestCase):
    """AssetPlatformsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetPlatformsApi()

    def tearDown(self) -> None:
        pass

    def test_asset_platforms_list(self) -> None:
        """Test case for asset_platforms_list

        Asset Platforms List (ID Map)
        """
        pass

    def test_token_lists(self) -> None:
        """Test case for token_lists

        👑 Token Lists by Asset Platform ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
