# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.coins_data_base_market_data_price_change_percentage24h_in_currency import CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency

class TestCoinsDataBaseMarketDataPriceChangePercentage24hInCurrency(unittest.TestCase):
    """CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency:
        """Test CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency`
        """
        model = CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency()
        if include_optional:
            return CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency(
                btc = 1.337,
                eur = 1.337,
                usd = 1.337
            )
        else:
            return CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency(
        )
        """

    def testCoinsDataBaseMarketDataPriceChangePercentage24hInCurrency(self):
        """Test CoinsDataBaseMarketDataPriceChangePercentage24hInCurrency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
