# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.networks_list import NetworksList

class TestNetworksList(unittest.TestCase):
    """NetworksList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworksList:
        """Test NetworksList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworksList`
        """
        model = NetworksList()
        if include_optional:
            return NetworksList(
                data = [
                    coingecko_python.models.networks_list_data_inner.NetworksList_data_inner(
                        id = '', 
                        type = '', 
                        attributes = coingecko_python.models.networks_list_data_inner_attributes.NetworksList_data_inner_attributes(
                            name = '', 
                            coingecko_asset_platform_id = '', ), )
                    ]
            )
        else:
            return NetworksList(
        )
        """

    def testNetworksList(self):
        """Test NetworksList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
