# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.onchain_categories_list import OnchainCategoriesList

class TestOnchainCategoriesList(unittest.TestCase):
    """OnchainCategoriesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnchainCategoriesList:
        """Test OnchainCategoriesList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnchainCategoriesList`
        """
        model = OnchainCategoriesList()
        if include_optional:
            return OnchainCategoriesList(
                data = [
                    coingecko-sdk.models.onchain_categories_list_data_inner.OnchainCategoriesList_data_inner(
                        id = '', 
                        type = '', 
                        attributes = coingecko-sdk.models.onchain_categories_list_data_inner_attributes.OnchainCategoriesList_data_inner_attributes(
                            name = '', 
                            description = '', 
                            volume_change_percentage = coingecko-sdk.models.onchain_categories_list_data_inner_attributes_volume_change_percentage.OnchainCategoriesList_data_inner_attributes_volume_change_percentage(
                                h1 = '', 
                                h6 = '', 
                                h12 = '', 
                                h24 = '', ), 
                            reserve_in_usd = '', 
                            fdv_usd = '', 
                            h24_volume_usd = '', 
                            h24_tx_count = 56, ), )
                    ]
            )
        else:
            return OnchainCategoriesList(
        )
        """

    def testOnchainCategoriesList(self):
        """Test OnchainCategoriesList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
