# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.nft_market_chart import NFTMarketChart

class TestNFTMarketChart(unittest.TestCase):
    """NFTMarketChart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFTMarketChart:
        """Test NFTMarketChart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFTMarketChart`
        """
        model = NFTMarketChart()
        if include_optional:
            return NFTMarketChart(
                floor_price_usd = [
                    [
                        1.337
                        ]
                    ],
                floor_price_native = [
                    [
                        1.337
                        ]
                    ],
                h24_volume_usd = [
                    [
                        1.337
                        ]
                    ],
                h24_volume_native = [
                    [
                        1.337
                        ]
                    ],
                market_cap_usd = [
                    [
                        1.337
                        ]
                    ],
                market_cap_native = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return NFTMarketChart(
        )
        """

    def testNFTMarketChart(self):
        """Test NFTMarketChart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
