# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.derivatives_exchanges_id import DerivativesExchangesID

class TestDerivativesExchangesID(unittest.TestCase):
    """DerivativesExchangesID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DerivativesExchangesID:
        """Test DerivativesExchangesID
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DerivativesExchangesID`
        """
        model = DerivativesExchangesID()
        if include_optional:
            return DerivativesExchangesID(
                name = '',
                open_interest_btc = 1.337,
                trade_volume_24h_btc = '',
                number_of_perpetual_pairs = 1.337,
                number_of_futures_pairs = 1.337,
                image = '',
                year_established = 1.337,
                country = '',
                description = '',
                url = '',
                tickers = [
                    [{"market":"Deepcoin (Derivatives)","symbol":"ETHUSDT","index_id":"ETH","price":"3395.91","price_percentage_change_24h":1.5274069068216,"contract_type":"perpetual","index":3393.5342,"basis":-0.0523015571479482,"spread":0.01,"funding_rate":-0.007182,"open_interest":9.32799876466E9,"volume_24h":3.92642535232121E8,"last_traded_at":1712467658,"expired_at":null},{"market":"BYDFi (Futures)","symbol":"BTC-PERPUSDT","index_id":"BTC","price":"69434.1","price_percentage_change_24h":2.04057930105749,"contract_type":"perpetual","index":69407.5,"basis":-5.76303273834822E-4,"spread":0.01,"funding_rate":0.012,"open_interest":7.6902120576E9,"volume_24h":1.32888173547E8,"last_traded_at":1712467920,"expired_at":null}]
                    ]
            )
        else:
            return DerivativesExchangesID(
        )
        """

    def testDerivativesExchangesID(self):
        """Test DerivativesExchangesID"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
