# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.api.simple_api import SimpleApi


class TestSimpleApi(unittest.TestCase):
    """SimpleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimpleApi()

    def tearDown(self) -> None:
        pass

    def test_onchain_simple_price(self) -> None:
        """Test case for onchain_simple_price

        Token Price by Token Addresses
        """
        pass

    def test_simple_price(self) -> None:
        """Test case for simple_price

        Coin Price by IDs
        """
        pass

    def test_simple_supported_currencies(self) -> None:
        """Test case for simple_supported_currencies

        Supported Currencies List
        """
        pass

    def test_simple_token_price(self) -> None:
        """Test case for simple_token_price

        Coin Price by Token Addresses
        """
        pass


if __name__ == '__main__':
    unittest.main()
