# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.api.ohlcv_api import OHLCVApi


class TestOHLCVApi(unittest.TestCase):
    """OHLCVApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OHLCVApi()

    def tearDown(self) -> None:
        pass

    def test_pool_ohlcv_contract_address(self) -> None:
        """Test case for pool_ohlcv_contract_address

        Pool OHLCV chart by Pool Address
        """
        pass


if __name__ == '__main__':
    unittest.main()
