# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.api.coins_api import CoinsApi


class TestCoinsApi(unittest.TestCase):
    """CoinsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoinsApi()

    def tearDown(self) -> None:
        pass

    def test_coins_id(self) -> None:
        """Test case for coins_id

        Coin Data by ID
        """
        pass

    def test_coins_id_circulating_supply_chart(self) -> None:
        """Test case for coins_id_circulating_supply_chart

        👑 Circulating Supply Chart by ID
        """
        pass

    def test_coins_id_circulating_supply_chart_range(self) -> None:
        """Test case for coins_id_circulating_supply_chart_range

        👑 Circulating Supply Chart within Time Range by ID
        """
        pass

    def test_coins_id_history(self) -> None:
        """Test case for coins_id_history

        Coin Historical Data by ID
        """
        pass

    def test_coins_id_market_chart(self) -> None:
        """Test case for coins_id_market_chart

        Coin Historical Chart Data by ID
        """
        pass

    def test_coins_id_market_chart_range(self) -> None:
        """Test case for coins_id_market_chart_range

        Coin Historical Chart Data within Time Range by ID
        """
        pass

    def test_coins_id_ohlc(self) -> None:
        """Test case for coins_id_ohlc

        Coin OHLC Chart by ID
        """
        pass

    def test_coins_id_ohlc_range(self) -> None:
        """Test case for coins_id_ohlc_range

        💼 Coin OHLC Chart within Time Range by ID
        """
        pass

    def test_coins_id_tickers(self) -> None:
        """Test case for coins_id_tickers

        Coin Tickers by ID
        """
        pass

    def test_coins_id_total_supply_chart(self) -> None:
        """Test case for coins_id_total_supply_chart

        👑 Total Supply Chart by ID
        """
        pass

    def test_coins_id_total_supply_chart_range(self) -> None:
        """Test case for coins_id_total_supply_chart_range

        👑 Total Supply Chart within time range by ID
        """
        pass

    def test_coins_list(self) -> None:
        """Test case for coins_list

        Coins List (ID Map)
        """
        pass

    def test_coins_list_new(self) -> None:
        """Test case for coins_list_new

        💼 Recently Added Coins
        """
        pass

    def test_coins_markets(self) -> None:
        """Test case for coins_markets

        Coins List with Market Data
        """
        pass

    def test_coins_top_gainers_losers(self) -> None:
        """Test case for coins_top_gainers_losers

        💼 Top Gainers & Losers
        """
        pass


if __name__ == '__main__':
    unittest.main()
