# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.global_data import GlobalData

class TestGlobalData(unittest.TestCase):
    """GlobalData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalData:
        """Test GlobalData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalData`
        """
        model = GlobalData()
        if include_optional:
            return GlobalData(
                active_cryptocurrencies = 1.337,
                upcoming_icos = 1.337,
                ongoing_icos = 1.337,
                ended_icos = 1.337,
                markets = 1.337,
                total_market_cap = coingecko-sdk.models.global_data_total_market_cap.Global_data_total_market_cap(
                    btc = 1.337, 
                    eth = 1.337, ),
                total_volume = coingecko-sdk.models.global_data_total_volume.Global_data_total_volume(
                    btc = 1.337, 
                    eth = 1.337, ),
                market_cap_percentage = coingecko-sdk.models.global_data_market_cap_percentage.Global_data_market_cap_percentage(
                    btc = 1.337, 
                    eth = 1.337, )
            )
        else:
            return GlobalData(
        )
        """

    def testGlobalData(self):
        """Test GlobalData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
