# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.api.derivatives_api import DerivativesApi


class TestDerivativesApi(unittest.TestCase):
    """DerivativesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DerivativesApi()

    def tearDown(self) -> None:
        pass

    def test_derivatives_exchanges(self) -> None:
        """Test case for derivatives_exchanges

        Derivatives Exchanges List with Data
        """
        pass

    def test_derivatives_exchanges_id(self) -> None:
        """Test case for derivatives_exchanges_id

        Derivatives Exchange Data by ID
        """
        pass

    def test_derivatives_exchanges_list(self) -> None:
        """Test case for derivatives_exchanges_list

        Derivatives Exchanges List (ID Map)
        """
        pass

    def test_derivatives_tickers(self) -> None:
        """Test case for derivatives_tickers

        Derivatives Tickers List
        """
        pass


if __name__ == '__main__':
    unittest.main()
