# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.derivatives_tickers_list import DerivativesTickersList

class TestDerivativesTickersList(unittest.TestCase):
    """DerivativesTickersList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DerivativesTickersList:
        """Test DerivativesTickersList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DerivativesTickersList`
        """
        model = DerivativesTickersList()
        if include_optional:
            return DerivativesTickersList(
                market = '',
                symbol = '',
                index_id = '',
                price = '',
                price_percentage_change_24h = 1.337,
                contract_type = '',
                index = 1.337,
                basis = 1.337,
                spread = 1.337,
                funding_rate = 1.337,
                open_interest = 1.337,
                volume_24h = 1.337,
                last_traded_at = 1.337,
                expired_at = ''
            )
        else:
            return DerivativesTickersList(
        )
        """

    def testDerivativesTickersList(self):
        """Test DerivativesTickersList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
