# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.pool_data_inner import PoolDataInner

class TestPoolDataInner(unittest.TestCase):
    """PoolDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoolDataInner:
        """Test PoolDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoolDataInner`
        """
        model = PoolDataInner()
        if include_optional:
            return PoolDataInner(
                id = '',
                type = '',
                attributes = coingecko_python.models.pool_data_inner_attributes.Pool_data_inner_attributes(
                    base_token_price_usd = '', 
                    base_token_price_native_currency = '', 
                    quote_token_price_usd = '', 
                    quote_token_price_native_currency = '', 
                    base_token_price_quote_token = '', 
                    quote_token_price_base_token = '', 
                    address = '', 
                    name = '', 
                    pool_created_at = '', 
                    fdv_usd = '', 
                    market_cap_usd = '', 
                    price_change_percentage = coingecko_python.models.pool_data_inner_attributes_price_change_percentage.Pool_data_inner_attributes_price_change_percentage(
                        m5 = '', 
                        h1 = '', 
                        h6 = '', 
                        h24 = '', ), 
                    transactions = coingecko_python.models.pool_data_inner_attributes_transactions.Pool_data_inner_attributes_transactions(
                        m5 = coingecko_python.models.pool_data_inner_attributes_transactions_m5.Pool_data_inner_attributes_transactions_m5(
                            buys = 56, 
                            sells = 56, 
                            buyers = 56, 
                            sellers = 56, ), 
                        m15 = coingecko_python.models.pool_data_inner_attributes_transactions_m5.Pool_data_inner_attributes_transactions_m5(
                            buys = 56, 
                            sells = 56, 
                            buyers = 56, 
                            sellers = 56, ), 
                        m30 = , 
                        h1 = , 
                        h24 = , ), 
                    volume_usd = coingecko_python.models.pool_data_inner_attributes_price_change_percentage.Pool_data_inner_attributes_price_change_percentage(
                        h6 = '', ), 
                    reserve_in_usd = '', ),
                relationships = coingecko_python.models.pool_data_inner_relationships.Pool_data_inner_relationships(
                    base_token = coingecko_python.models.pool_data_inner_relationships_base_token.Pool_data_inner_relationships_base_token(
                        data = coingecko_python.models.pool_data_inner_relationships_base_token_data.Pool_data_inner_relationships_base_token_data(
                            id = '', 
                            type = '', ), ), 
                    quote_token = coingecko_python.models.pool_data_inner_relationships_base_token.Pool_data_inner_relationships_base_token(), 
                    network = , 
                    dex = , )
            )
        else:
            return PoolDataInner(
        )
        """

    def testPoolDataInner(self):
        """Test PoolDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
