# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.nft_data_floor_price30d_percentage_change import NFTDataFloorPrice30dPercentageChange

class TestNFTDataFloorPrice30dPercentageChange(unittest.TestCase):
    """NFTDataFloorPrice30dPercentageChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFTDataFloorPrice30dPercentageChange:
        """Test NFTDataFloorPrice30dPercentageChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFTDataFloorPrice30dPercentageChange`
        """
        model = NFTDataFloorPrice30dPercentageChange()
        if include_optional:
            return NFTDataFloorPrice30dPercentageChange(
                usd = 1.337,
                native_currency = 1.337
            )
        else:
            return NFTDataFloorPrice30dPercentageChange(
        )
        """

    def testNFTDataFloorPrice30dPercentageChange(self):
        """Test NFTDataFloorPrice30dPercentageChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
