# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.trending_search_coins_inner import TrendingSearchCoinsInner

class TestTrendingSearchCoinsInner(unittest.TestCase):
    """TrendingSearchCoinsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendingSearchCoinsInner:
        """Test TrendingSearchCoinsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrendingSearchCoinsInner`
        """
        model = TrendingSearchCoinsInner()
        if include_optional:
            return TrendingSearchCoinsInner(
                id = '',
                coin_id = 1.337,
                name = '',
                symbol = '',
                market_cap_rank = 1.337,
                thumb = '',
                small = '',
                large = '',
                slug = '',
                price_btc = 1.337,
                score = 1.337,
                data = coingecko_python.models.trending_search_coins_inner_data.TrendingSearch_coins_inner_data(
                    price = 1.337, 
                    price_btc = '', 
                    price_change_percentage_24h = coingecko_python.models.trending_search_coins_inner_data_price_change_percentage_24h.TrendingSearch_coins_inner_data_price_change_percentage_24h(
                        btc = 1.337, 
                        usd = 1.337, ), 
                    market_cap = '', 
                    market_cap_btc = '', 
                    total_volume = '', 
                    total_volume_btc = '', 
                    sparkline = '', 
                    content = '', )
            )
        else:
            return TrendingSearchCoinsInner(
        )
        """

    def testTrendingSearchCoinsInner(self):
        """Test TrendingSearchCoinsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
