# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.pool_data_inner_attributes_transactions_m5 import PoolDataInnerAttributesTransactionsM5

class TestPoolDataInnerAttributesTransactionsM5(unittest.TestCase):
    """PoolDataInnerAttributesTransactionsM5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoolDataInnerAttributesTransactionsM5:
        """Test PoolDataInnerAttributesTransactionsM5
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoolDataInnerAttributesTransactionsM5`
        """
        model = PoolDataInnerAttributesTransactionsM5()
        if include_optional:
            return PoolDataInnerAttributesTransactionsM5(
                buys = 56,
                sells = 56,
                buyers = 56,
                sellers = 56
            )
        else:
            return PoolDataInnerAttributesTransactionsM5(
        )
        """

    def testPoolDataInnerAttributesTransactionsM5(self):
        """Test PoolDataInnerAttributesTransactionsM5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
