# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.models.top_gainers_losers_inner import TopGainersLosersInner

class TestTopGainersLosersInner(unittest.TestCase):
    """TopGainersLosersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TopGainersLosersInner:
        """Test TopGainersLosersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TopGainersLosersInner`
        """
        model = TopGainersLosersInner()
        if include_optional:
            return TopGainersLosersInner(
                id = '',
                symbol = '',
                name = '',
                image = '',
                market_cap_rank = 1.337,
                usd = 1.337,
                usd_24h_vol = 1.337,
                usd_1y_change = 1.337
            )
        else:
            return TopGainersLosersInner(
        )
        """

    def testTopGainersLosersInner(self):
        """Test TopGainersLosersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
