# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.models.nft_tickers import NFTTickers

class TestNFTTickers(unittest.TestCase):
    """NFTTickers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NFTTickers:
        """Test NFTTickers
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NFTTickers`
        """
        model = NFTTickers()
        if include_optional:
            return NFTTickers(
                tickers = [
                    coingecko_sdk.models.nft_tickers_tickers_inner.NFTTickers_tickers_inner(
                        floor_price_in_native_currency = 1.337, 
                        h24_volume_in_native_currency = 1.337, 
                        native_currency = '', 
                        native_currency_symbol = '', 
                        updated_at = '', 
                        nft_marketplace_id = '', 
                        name = '', 
                        image = '', 
                        nft_collection_url = '', )
                    ]
            )
        else:
            return NFTTickers(
        )
        """

    def testNFTTickers(self):
        """Test NFTTickers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
