# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.models.coins_historical_data_market_data_total_volume import CoinsHistoricalDataMarketDataTotalVolume

class TestCoinsHistoricalDataMarketDataTotalVolume(unittest.TestCase):
    """CoinsHistoricalDataMarketDataTotalVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoinsHistoricalDataMarketDataTotalVolume:
        """Test CoinsHistoricalDataMarketDataTotalVolume
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoinsHistoricalDataMarketDataTotalVolume`
        """
        model = CoinsHistoricalDataMarketDataTotalVolume()
        if include_optional:
            return CoinsHistoricalDataMarketDataTotalVolume(
                btc = 1.337,
                eur = 1.337,
                usd = 1.337
            )
        else:
            return CoinsHistoricalDataMarketDataTotalVolume(
        )
        """

    def testCoinsHistoricalDataMarketDataTotalVolume(self):
        """Test CoinsHistoricalDataMarketDataTotalVolume"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
