# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.coins_data_base_developer_data import CoinsDataBaseDeveloperData

class TestCoinsDataBaseDeveloperData(unittest.TestCase):
    """CoinsDataBaseDeveloperData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoinsDataBaseDeveloperData:
        """Test CoinsDataBaseDeveloperData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoinsDataBaseDeveloperData`
        """
        model = CoinsDataBaseDeveloperData()
        if include_optional:
            return CoinsDataBaseDeveloperData(
                forks = 1.337,
                stars = 1.337,
                subscribers = 1.337,
                total_issues = 1.337,
                closed_issues = 1.337,
                pull_requests_merged = 1.337,
                pull_request_contributors = 1.337,
                code_additions_deletions_4_weeks = coingecko-sdk.models.coins_data_base_developer_data_code_additions_deletions_4_weeks.CoinsDataBase_developer_data_code_additions_deletions_4_weeks(
                    additions = 1.337, 
                    deletions = 1.337, ),
                commit_count_4_weeks = 1.337,
                last_4_weeks_commit_activity_series = []
            )
        else:
            return CoinsDataBaseDeveloperData(
        )
        """

    def testCoinsDataBaseDeveloperData(self):
        """Test CoinsDataBaseDeveloperData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
