# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.models.token_lists import TokenLists

class TestTokenLists(unittest.TestCase):
    """TokenLists unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenLists:
        """Test TokenLists
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenLists`
        """
        model = TokenLists()
        if include_optional:
            return TokenLists(
                name = '',
                logo_uri = '',
                keywords = [
                    ''
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tokens = [
                    coingecko_sdk.models.token_lists_tokens_inner.TokenLists_tokens_inner(
                        chain_id = 1.337, 
                        address = '', 
                        name = '', 
                        symbol = '', 
                        decimals = 1.337, 
                        logo_uri = '', )
                    ]
            )
        else:
            return TokenLists(
        )
        """

    def testTokenLists(self):
        """Test TokenLists"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
