# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.onchain_categories_list_data_inner_attributes_volume_change_percentage import OnchainCategoriesListDataInnerAttributesVolumeChangePercentage

class TestOnchainCategoriesListDataInnerAttributesVolumeChangePercentage(unittest.TestCase):
    """OnchainCategoriesListDataInnerAttributesVolumeChangePercentage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnchainCategoriesListDataInnerAttributesVolumeChangePercentage:
        """Test OnchainCategoriesListDataInnerAttributesVolumeChangePercentage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnchainCategoriesListDataInnerAttributesVolumeChangePercentage`
        """
        model = OnchainCategoriesListDataInnerAttributesVolumeChangePercentage()
        if include_optional:
            return OnchainCategoriesListDataInnerAttributesVolumeChangePercentage(
                h1 = '',
                h6 = '',
                h12 = '',
                h24 = ''
            )
        else:
            return OnchainCategoriesListDataInnerAttributesVolumeChangePercentage(
        )
        """

    def testOnchainCategoriesListDataInnerAttributesVolumeChangePercentage(self):
        """Test OnchainCategoriesListDataInnerAttributesVolumeChangePercentage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
