# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.models.simple_token_price import SimpleTokenPrice

class TestSimpleTokenPrice(unittest.TestCase):
    """SimpleTokenPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimpleTokenPrice:
        """Test SimpleTokenPrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimpleTokenPrice`
        """
        model = SimpleTokenPrice()
        if include_optional:
            return SimpleTokenPrice(
                usd = 1.337,
                usd_market_cap = 1.337,
                usd_24h_vol = 1.337,
                usd_24h_change = 1.337,
                last_updated_at = 1.337
            )
        else:
            return SimpleTokenPrice(
        )
        """

    def testSimpleTokenPrice(self):
        """Test SimpleTokenPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
