# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.coins_data_base_community_data import CoinsDataBaseCommunityData

class TestCoinsDataBaseCommunityData(unittest.TestCase):
    """CoinsDataBaseCommunityData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoinsDataBaseCommunityData:
        """Test CoinsDataBaseCommunityData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoinsDataBaseCommunityData`
        """
        model = CoinsDataBaseCommunityData()
        if include_optional:
            return CoinsDataBaseCommunityData(
                facebook_likes = 1.337,
                twitter_followers = 1.337,
                reddit_average_posts_48h = 1.337,
                reddit_average_comments_48h = 1.337,
                reddit_subscribers = 1.337,
                reddit_accounts_active_48h = 1.337,
                telegram_channel_user_count = 1.337
            )
        else:
            return CoinsDataBaseCommunityData(
        )
        """

    def testCoinsDataBaseCommunityData(self):
        """Test CoinsDataBaseCommunityData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
