# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.onchain_simple_price import OnchainSimplePrice

class TestOnchainSimplePrice(unittest.TestCase):
    """OnchainSimplePrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnchainSimplePrice:
        """Test OnchainSimplePrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnchainSimplePrice`
        """
        model = OnchainSimplePrice()
        if include_optional:
            return OnchainSimplePrice(
                data = coingecko_python.models.onchain_simple_price_data.OnchainSimplePrice_data(
                    id = '', 
                    type = '', 
                    attributes = coingecko_python.models.onchain_simple_price_data_attributes.OnchainSimplePrice_data_attributes(
                        token_prices = {
                            'key' : ''
                            }, ), )
            )
        else:
            return OnchainSimplePrice(
        )
        """

    def testOnchainSimplePrice(self):
        """Test OnchainSimplePrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
