# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.coins_historical_data_market_data import CoinsHistoricalDataMarketData

class TestCoinsHistoricalDataMarketData(unittest.TestCase):
    """CoinsHistoricalDataMarketData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoinsHistoricalDataMarketData:
        """Test CoinsHistoricalDataMarketData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoinsHistoricalDataMarketData`
        """
        model = CoinsHistoricalDataMarketData()
        if include_optional:
            return CoinsHistoricalDataMarketData(
                current_price = coingecko_python.models.coins_historical_data_market_data_current_price.CoinsHistoricalData_market_data_current_price(
                    btc = 1.337, 
                    eur = 1.337, 
                    usd = 1.337, ),
                market_cap = coingecko_python.models.coins_historical_data_market_data_market_cap.CoinsHistoricalData_market_data_market_cap(
                    btc = 1.337, 
                    eur = 1.337, 
                    usd = 1.337, ),
                total_volume = coingecko_python.models.coins_historical_data_market_data_total_volume.CoinsHistoricalData_market_data_total_volume(
                    btc = 1.337, 
                    eur = 1.337, 
                    usd = 1.337, )
            )
        else:
            return CoinsHistoricalDataMarketData(
        )
        """

    def testCoinsHistoricalDataMarketData(self):
        """Test CoinsHistoricalDataMarketData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
