# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.token_data_attributes import TokenDataAttributes

class TestTokenDataAttributes(unittest.TestCase):
    """TokenDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenDataAttributes:
        """Test TokenDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenDataAttributes`
        """
        model = TokenDataAttributes()
        if include_optional:
            return TokenDataAttributes(
                address = '',
                name = '',
                symbol = '',
                image_url = '',
                coingecko_coin_id = '',
                decimals = 56,
                total_supply = '',
                price_usd = '',
                fdv_usd = '',
                total_reserve_in_usd = '',
                volume_usd = coingecko-sdk.models.token_data_attributes_volume_usd.Token_data_attributes_volume_usd(
                    h24 = '', ),
                market_cap_usd = ''
            )
        else:
            return TokenDataAttributes(
        )
        """

    def testTokenDataAttributes(self):
        """Test TokenDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
