# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_sdk.models.key import Key

class TestKey(unittest.TestCase):
    """Key unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Key:
        """Test Key
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Key`
        """
        model = Key()
        if include_optional:
            return Key(
                plan = '',
                rate_limit_request_per_minute = 1.337,
                monthly_call_credit = 1.337,
                current_total_monthly_calls = 1.337,
                current_remaining_monthly_calls = 1.337
            )
        else:
            return Key(
        )
        """

    def testKey(self):
        """Test Key"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
