# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko_python.models.categories import Categories

class TestCategories(unittest.TestCase):
    """Categories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Categories:
        """Test Categories
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Categories`
        """
        model = Categories()
        if include_optional:
            return Categories(
                id = '',
                name = '',
                market_cap = 1.337,
                market_cap_change_24h = 1.337,
                content = '',
                top_3_coins_id = [
                    ''
                    ],
                top_3_coins = [
                    ''
                    ],
                volume_24h = 1.337,
                updated_at = ''
            )
        else:
            return Categories(
        )
        """

    def testCategories(self):
        """Test Categories"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
