# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coingecko-sdk.models.pool_tokens_info import PoolTokensInfo

class TestPoolTokensInfo(unittest.TestCase):
    """PoolTokensInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoolTokensInfo:
        """Test PoolTokensInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoolTokensInfo`
        """
        model = PoolTokensInfo()
        if include_optional:
            return PoolTokensInfo(
                data = coingecko-sdk.models.token_info_data.TokenInfo_data(
                    id = '', 
                    type = '', 
                    attributes = coingecko-sdk.models.token_info_data_attributes.TokenInfo_data_attributes(
                        address = '', 
                        name = '', 
                        symbol = '', 
                        image_url = '', 
                        coingecko_coin_id = '', 
                        websites = [
                            ''
                            ], 
                        description = '', 
                        gt_score = 1.337, 
                        discord_url = '', 
                        telegram_handle = '', 
                        twitter_handle = '', 
                        categories = [
                            ''
                            ], 
                        gt_categories_id = [
                            ''
                            ], 
                        holders = coingecko-sdk.models.token_info_data_attributes_holders.TokenInfo_data_attributes_holders(
                            count = 56, 
                            distribution_percentage = coingecko-sdk.models.token_info_data_attributes_holders_distribution_percentage.TokenInfo_data_attributes_holders_distribution_percentage(
                                top_10 = 1.337, 
                                11_30 = 1.337, 
                                31_50 = 1.337, 
                                rest = 1.337, ), 
                            last_updated = '', ), ), )
            )
        else:
            return PoolTokensInfo(
        )
        """

    def testPoolTokensInfo(self):
        """Test PoolTokensInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
