# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CoinsDataBaseCommunityData(BaseModel):
    """
    coin community data
    """ # noqa: E501
    facebook_likes: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin facebook likes")
    twitter_followers: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin twitter followers")
    reddit_average_posts_48h: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin reddit average posts in 48 hours")
    reddit_average_comments_48h: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin reddit average comments in 48 hours")
    reddit_subscribers: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin reddit subscribers")
    reddit_accounts_active_48h: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin reddit active accounts in 48 hours")
    telegram_channel_user_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="coin telegram channel user count")
    __properties: ClassVar[List[str]] = ["facebook_likes", "twitter_followers", "reddit_average_posts_48h", "reddit_average_comments_48h", "reddit_subscribers", "reddit_accounts_active_48h", "telegram_channel_user_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoinsDataBaseCommunityData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoinsDataBaseCommunityData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "facebook_likes": obj.get("facebook_likes"),
            "twitter_followers": obj.get("twitter_followers"),
            "reddit_average_posts_48h": obj.get("reddit_average_posts_48h"),
            "reddit_average_comments_48h": obj.get("reddit_average_comments_48h"),
            "reddit_subscribers": obj.get("reddit_subscribers"),
            "reddit_accounts_active_48h": obj.get("reddit_accounts_active_48h"),
            "telegram_channel_user_count": obj.get("telegram_channel_user_count")
        })
        return _obj


