# coding: utf-8

"""
    CoinGecko API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class NFTMarketChart(BaseModel):
    """
    NFTMarketChart
    """ # noqa: E501
    floor_price_usd: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="NFT collection floor price in usd")
    floor_price_native: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="NFT collection floor price in native currency")
    h24_volume_usd: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="NFT collection volume in 24 hours in usd")
    h24_volume_native: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="NFT collection volume in 24 hours in native currency")
    market_cap_usd: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="NFT collection market cap in usd")
    market_cap_native: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="NFT collection market cap in native currency")
    __properties: ClassVar[List[str]] = ["floor_price_usd", "floor_price_native", "h24_volume_usd", "h24_volume_native", "market_cap_usd", "market_cap_native"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NFTMarketChart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NFTMarketChart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "floor_price_usd": obj.get("floor_price_usd"),
            "floor_price_native": obj.get("floor_price_native"),
            "h24_volume_usd": obj.get("h24_volume_usd"),
            "h24_volume_native": obj.get("h24_volume_native"),
            "market_cap_usd": obj.get("market_cap_usd"),
            "market_cap_native": obj.get("market_cap_native")
        })
        return _obj


